name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: node install
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: npm init
        run: npm init -y

      - name: Install semantic-release
        run: npm install --save-dev semantic-release
      
      - name: Install @semantic-release/changelog
        run: npm install --save-dev @semantic-release/changelog
      
      - name: Install @semantic-release/git
        run: npm install --save-dev @semantic-release/git
      
      - name: Install @semantic-release/github
        run: npm install --save-dev @semantic-release/github
      
      - name: Install @semantic-release/commit-analyzer
        run: npm install --save-dev @semantic-release/commit-analyzer
      
      - name: Install @semantic-release/release-notes-generator
        run: npm install --save-dev @semantic-release/release-notes-generator

      - name: semantic-release execution
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: semantic-release:*
        run: npx semantic-release